MKSHELL=/bin/bash

## Load configurations from file
## Config file contains paths to Reference Genome, Intervals of interest, executables
< config.mk

## Calculate depth of coverage

## TARGET:atributes: PREREQ
results/%.sample_interval_summary: data/%.bam 
	set -x
	mkdir -p $(dirname $target)
	#Run GATK for depth of coverage:
	echo "[DEBUGGING] Calculating depth of coverage for one bam file..."
	java -Xmx3072m -jar $GATK \
		-T DepthOfCoverage -I $prereq -L $INTERVALS \
		-R $REFERENCE \
		-dt BY_SAMPLE -dcov 5000 -l INFO --omitDepthOutputAtEachBase --omitLocusTable \
		--minBaseQuality 0 --minMappingQuality 20 --start 1 --stop 5000 --nBins 200 \
		--includeRefNSites \
		--countType COUNT_FRAGMENTS \
		-o results/$stem.build \
	&& mv results/$stem.build.sample_interval_statistics results/$stem.sample_interval_statistics \
	&& mv results/$stem.build.sample_summary results/$stem.sample_summary \
	&& mv results/$stem.build.sample_statistics results/$stem.sample_statistics \
	&& mv results/$stem.build.sample_interval_summary results/$stem.sample_interval_summary 

