MKSHELL=/bin/bash

## Load configurations from file
## Config file contains paths to xhmm executables
< config.mk

## Combines and transforms GATK Depth-of-Coverage outputs for multiple samples (at same loci) in a list:
## here the input file is a list with depth of coverage information, this is created when executing the create-targets file
## Note that in this case it is necessary to apply the parameter --GATKdepthList to indicate the type of input file

## TARGET:atributes: PREREQ
results/%.RD.txt: data/%.sample_interval_summary.list 
        set -x
        mkdir -p $(dirname $target)
        #Run mergeGATKdepths and transform to xhmm format:
        echo "[DEBUGGING] Transforming data to xhmm format..."
        $XHMM --mergeGATKdepths -o $target.build \
	--GATKdepthsList $prereq \
	&& mv $target.build $target


