MKSHELL=/bin/bash

## Load configurations from file
## Config file contains paths to xhmm executables
< config.mk

# 01 Filters original read-depth data to be the same as filtered, normalized data:
## TARGET:atributes: PREREQ
results/%.original.normal_filtered.txt: data/%.centered data/%.centered.filtered_targets.txt results/%.zscores.PCA.filtered_targets.txt data/%.centered.filtered_samples.txt results/%.zscores.PCA.filtered_samples.txt
	set -x
        mkdir -p $(dirname $target)
	echo "Filtering original read-depth..."
	echo $target
	echo $prereq
	$XHMM \
		--matrix -r data/$stem.centered \
		--excludeTargets data/$stem.centered.filtered_targets.txt \
		--excludeTargets results/$stem.zscores.PCA.filtered_targets.txt \
		--excludeSamples data/$stem.centered.filtered_samples.txt \
		--excludeSamples results/$stem.zscores.PCA.filtered_samples.txt \
		-o results/$stem.original.normal_filtered.txt.build \
	&& mv results/$stem.original.normal_filtered.txt.build results/$stem.original.normal_filtered.txt

## 02 Filters and z-score centers (by sample) the PCA-normalized data:
## TARGET:atributes: PREREQ
results/%.zscores.PCA.filtered_samples.txt results/%.zscores.PCA.filtered_targets.txt results/%.zscores.PCA.txt: results/%.PCA_normalized.txt
        set -x
        mkdir -p $(dirname $target)
        echo "Filtering and get z-scores from PCA-normalized data..."
        $XHMM \
		--matrix -r $prereq --centerData --centerType sample --zScoreData \
		-o results/$stem.zscores.PCA.txt.build \
		--outputExcludedTargets results/$stem.zscores.PCA.filtered_targets.txt.build \
		--outputExcludedSamples results/$stem.zscores.PCA.filtered_samples.txt.build \
		--maxSdTargetRD 100 \
	&& mv results/$stem.zscores.PCA.txt.build results/$stem.zscores.PCA.txt \
	&& mv results/$stem.zscores.PCA.filtered_targets.txt.build results/$stem.zscores.PCA.filtered_targets.txt \
	&& mv results/$stem.zscores.PCA.filtered_samples.txt.build results/$stem.zscores.PCA.filtered_samples.txt

## 03 Filters samples and targets and then mean-centers the targets:
## Requires files produced during the PCA
## TARGET:atributes: PREREQ
results/%.PCA_normalized.num_removed_PC.txt results/%.PCA_normalized.txt: data/%.centered results/%.RD_PCA.PC.txt
        set -x
        mkdir -p $(dirname $target)
        #Normalizes mean-centered data using PCA information:
        echo "Normalizing mean-centered data using PCA information..."
        prereq1=data/$stem.centered
        prereq2=results/$stem.RD_PCA
        echo $target
        echo $prereq1
        echo $prereq2
	$XHMM \
		--normalize -r $prereq1 \
		--PCAfiles $prereq2 \
		--normalizeOutput results/$stem.PCA_normalized.build \
		--PCnormalizeMethod PVE_mean --PVE_mean_factor 0.7 \
		&& mv results/$stem.PCA_normalized.build results/$stem.PCA_normalized.txt \
		&& mv results/$stem.PCA_normalized.build.num_removed_PC.txt results/$stem.PCA_normalized.num_removed_PC.txt

## 04 Filters samples and targets and then mean-centers the targets:
## TARGET:atributes: PREREQ
results/%.RD_PCA.PC.txt: data/%.centered
	set -x
	mkdir -p $(dirname $target)
	#Run PCA on mean-centered data...
	echo "[DEBUGGING] Running PCA on mean-centered data..."
	echo $target
	echo $prereq
	$XHMM \
		--PCA -r $prereq \
		--PCAfiles results/$stem.RD_PCA.build \
	&& mv results/$stem.RD_PCA.build.PC_LOADINGS.txt results/$stem.RD_PCA.PC_LOADINGS.txt \
	&& mv results/$stem.RD_PCA.build.PC_SD.txt results/$stem.RD_PCA.PC_SD.txt \
	&& mv results/$stem.RD_PCA.build.PC.txt results/$stem.RD_PCA.PC.txt


